name: Convert Asciidoc to HTML and Deploy

on:
  push:
    branches: [main]
    paths: ["docs/**/*.adoc"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Asciidoctor
        run: sudo apt-get update && sudo apt-get install -y asciidoctor

      - name: Convert Asciidoc to HTML
        run: |
          for file in docs/**/*.adoc; do
            filename=$(basename "$file" .adoc)
            asciidoctor -o "docs/${filename}.html" "$file"
          done

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
