name: Conditions
on: push
jobs:
  skip-or-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"
        if: ${{ contains(github.run_id, '1') }}
      - run: exit 1
      - run: echo "Hello Failure!"
        if: ${{ failure() }}
  cancel:
    if: ${{ github.actor == 'octocat'}}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello Cancel!"
      