name: Dynamic matrix
on: push
env:
  TIMEOUT: 1
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - id: dynamic
        run: | #マトリックス定義を JSON 文字列で記述
          json='{"runner": ["ubuntu-latest", "macos-latest"]}'
          echo "json=${json}" >> "${GITHUB_OUTPUT}"
    outputs:
      matrix-json: ${{ steps.dynamic.outputs.json }}
  print:
    timeout-minutes: ${{ fromJSON(env.TIMEOUT) }}
    needs: [prepare]
    strategy:
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix-json) }}
    runs-on: ${{ matrix.runner }}
    steps:
      - run: echo "${RUNNER_OS}"