name: Intermediate environment variables
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      ACTOR: ${{ github.actor }}
      USERNAME: ${{ vars.USERNAME }}
    steps:
      - run: echo "${BRANCH}"
      - run: echo "${ACTOR}"
      - run: echo "${USERNAME}"
