name: Compare functions
on: push
jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep "_FUNC"
        env:
          CONTAINS_FUNC: ${{ contains('Hello', 'ell') }}
          STARTS_WITH_FUNC: ${{ startsWith('Hello', 'He') }}
          ENDS_WITH_FUNC: ${{ endsWith('Hello', 'lo')}}
          CONTAINS_2_FUNC: ${{ contains(github.event.issue.labels.*.name, 'bug') }}
          FORMAT_FUNC: ${{ format('{0}, {1}', 'Hi', 'world') }}
          JOIN_FUNC: ${{ join(github.event.*.html_url, ',') }}
      - run: echo "${CONTEXT}"
        env:
          CONTEXT: ${{ toJSON(github) }}
      - uses: actions/checkout@v5.0.0
      - run: echo "${HASH}"
        env:
          HASH: ${{ hashFiles('.github/workflows/*.yml') }}
