name: Schedule
on:
  schedule:
    - cron: '*/60 * * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job runs every hour as per the schedule."
      - run: date
      - run: echo "Scheduled workflow executed successfully!" 